name = "barbier-berlin"
pages_build_output_dir = "./dist"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "barbier-berlin-db"
database_id = "9593e083-6cf8-4dac-b012-37ef5db04ac7"
migrations_dir = "drizzle/migrations"
